### ISSUE TITLE
add run verbose

### ISSUE THREAD

**Issue by slav** [mausch/UrchiNet#5]
It would be nice to have a verbose runner that prints out information about tests progress as tests are run. It could print test just finished, % total done, etc.

The point is to give better feedback when I manually run the tests to see the progress.

**Comment by mausch** [comment]
Hi, did you mean to post this on https://github.com/mausch/Fuchu ?

**Comment by slav** [comment]
@mausch - yes, I'm really sorry. Was exploring and didn't notice wasn't in the right repository.
